sudo: required

language: java

services:
 - docker

script:
 - ./gradlew installDist
 - docker build --tag=cnuss/memhog-service:travis_$TRAVIS_BUILD_NUMBER .
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" https://index.docker.io/v1/
 - docker push cnuss/memhog-service:travis_$TRAVIS_BUILD_NUMBER
